cask "alfred"
cask "istat-menus@5"
cask "thecontinium/tap/launchcontrol@1", trusted: true
cask "thecontinium/tap/marked-app@2", trusted: true
cask "thecontinium/tap/moom@3", trusted: true
cask "omnifocus"
cask "1password@7"
cask "switchresx"
cask "resilio-sync"
mas "Airmail", id: 918858936
mas "Habitify", id: 1111447047
mas "PCalc", id: 403504866
mas "Slack", id: 803453959
mas "Calory", id: 1476831360
