cask "alfred"
cask "istat-server"
cask "istat-menus"
cask "launchcontrol"
cask "little-snitch"
cask "marked"
cask "moom"
cask "omnifocus"
cask "1password"
cask "switchresx"
mas "Airmail 3", id: 918858936
mas "Habitify", id: 1140787122
mas "Notability", id: 736189492
mas "PCalc", id: 403504866
