# neovim
brew "neovim"
# neovim head build
brew "cmake"
brew "luarocks"
brew "pkg-config"
# snacks image
brew "imagemagick"
# python matplotlib-backend-terminal
brew "chafa"
# jupytext.nvim
brew "jupytext"
