# neovim
brew "neovim"
# neovim head build
brew "cmake"
brew "luarocks"
brew "pkg-config"
# nvim-treesitter
brew "tree-sitter-cli"
# snacks image
brew "imagemagick"
# snacks image svg conver by magick
brew "inkscape"
# snacks image latex
brew "tectonic"
# python matplotlib-backend-terminal
brew "chafa"
# jupytext.nvim
brew "jupytext"
